
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Feb 20 2020 08:40:57 GMT+0100 (GMT+01:00)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class ArticleExampleContentType extends ContentItem {
  public body!: Elements.RichTextElement;
  public title!: Elements.TextElement;
  public url!: Elements.UrlSlugElement;
}
