import { IContentItem, Elements } from "@kontent-ai/delivery-sdk";

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type LandingPageExampleContentType = IContentItem<{
  body: Elements.RichTextElement;
  productList: Elements.LinkedItemsElement<IContentItem>;
  title: Elements.TextElement;
  url: Elements.UrlSlugElement;
}>;
