
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Thu Jun 06 2019 14:16:39 GMT+0200 (GMT+02:00).
 *
 * Note: You can substitute 'ContentItem' type with another generated class. Generator doesn't have this information available
 * and so its up to you to define relationship between models.
 */
export class ProductExampleContentType extends ContentItem {
    public description!: Elements.RichTextElement;
    public name!: Elements.TextElement;
    public image!: Elements.AssetsElement;
    public taxonomyCategorizingTargetAudience!: Elements.TaxonomyElement;
    public url!: Elements.UrlSlugElement;
    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'taxonomy___categorizing_target_audience') {
                    return 'taxonomyCategorizingTargetAudience';
                }
                return fieldName;
            })
        });
    }
}
