name: Integrate

on:
  push:
    branches: [ master ]
  pull_request:
  
env:
  NODE_ENV: "production"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

      id: nvm
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
    - run: npm ci
    - run: npm run test -- --watchAll=false --passWithNoTests
    - run: npm run build
    - name: "Artifact : site"
      uses: actions/upload-artifact@v2
      with:
        name: "Site"
        path: ./build     
    - name: Deploy 🚀
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
        CLEAN: true # Automatically remove deleted files from the deploy branch
